# UI
base.url=https://stage.truckingtalent.com/
browser=chrome

# API
!поменять на правильный адрес, пока не знаю где его взять
api.url=https://stage.truckingtalent.com/
# нужно ли прописывать токены?
